name: Tic-Tac-Toe CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        qt-version: ['5.15.2']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        modules: 'qtcore qtgui qtwidgets qttest'

    - name: Create Build Directory
      run: mkdir build
      
    - name: Configure CMake
      working-directory: build
      run: cmake ..

    - name: Build
      working-directory: build
      run: cmake --build . --config Release

    - name: Run Tests
      working-directory: build
      run: ctest -C Release --output-on-failure

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.os }}
        path: build/Testing/Temporary/LastTest.log
        if-no-files-found: ignore 